FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download -x
COPY . .
RUN go mod tidy && go build -o notification-service .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/notification-service .
EXPOSE 3004
CMD ["./notification-service"]
